### ISSUE TITLE
Add ability to append a branch step

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1117]
Epic: https://github.com/KaotoIO/kaoto-ui/issues/783

## Tasks
- [x] Update `isLastNode` to support nested steps
- [x] ~~Update `isEndStep` to support nested steps?~~ ended up not being necessary.
- [x] Enable plus button for branch steps
- [x] Update `onMiniCatalogClickAdd` to support nested steps
- [x] Check that `appendableStepTypes` validation works for both branch steps and normal steps
