### ISSUE TITLE
Add support for minBranches/maxBranches

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1143]
### Please describe the feature that you want to propose

Some EIP steps require a minimum number of branches, so, once we support adding branches visually, we should verify that the minimum and maximum number of branches are correct.

## Requirements
1. If the user does not have enough branches, we should create the branches for the user automatically either via the backend or frontend. Alternatively, we can simply flag it to the user either in the visualization or in a step extension (preferably in the visualization).
2. If the user has the maximum number of branches, the button to add more branches should be hidden or disabled.

## Tasks

- [x] Hide `delete` button for edge for x number of edges if the step has a minimum number of branches
- [x] Hide branches tab if the step has the same amount as max branch
- [ ] Hide plus button if the step doesn't support branching and has already reached the maximum number of branches? Would that confuse users? Or maybe I can just disable it..
- [x] Custom tooltip message for mini catalog branches tab
- [ ] Auto-create minimum number of required branches?

requires #786

**Comment by kahboom** [comment]
@Delawen can we do the last task automatically from the backend? for automatically creating the number of required branches, or is it preferred this be done on the frontend?
