### ISSUE TITLE
Branching: Show branches even if empty

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1158]
### Please describe the feature that you want to propose

At the moment we don't show branches in the Visualization unless they contain at least one step. In preparation for creating branches visually, we need to be able to see when branches are empty. One way to show the branch if it's empty is to include a placeholder in the branch.

### Tasks
- [x] Remove edges for empty branches
- [x] Add placeholder node for empty branches
- [x] Add edge from root parent to placeholder in branch
- [x] Give placeholders a UUID, add a boolean flag instead
- [x] Add edge from placeholder to next step
- [x] Bug fix: Provide correct validation message for replacing steps
- [x] Ensure can replace/drop a step onto branch placeholder
- [x] Clicking placeholder should open catalog, not step detail view
