### ISSUE TITLE
Branching: Add ability to insert step after a step that contains branches

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1162]
### Please describe the feature that you want to propose

At the moment, it's not possible to insert a step between a step that contains branches, and the next step.

In the example below, it would be the equivalent of inserting a step between the root `filter` step and `kamelet:sink` (but not _within_ the `filter` branch):

![Screen Shot 2023-01-19 at 11 41 54 am copy 4](https://user-images.githubusercontent.com/3844502/214293124-4a2506df-b5c1-4154-b63d-79d2753ea62f.png)

In essence, this would be the same as prepending a step (similarly to how we are intending to do for branch steps, #1161 ), for the `kamelet:sink` step, and so should only be necessary for this kind of step (the step _after_ a step that contains branches), otherwise you would normally use `insertStep`.

Relates to #140 and should consider what happens visually when groups are collapsed (#772).

### Tasks
- [x] Make prepend step show up for steps whose previous step contains branches
- [x] Check for steps within branches with the same conditions
- [x] Handle prepending for both scenarios

**Comment by lhein** [comment]
Isn't that already working by using the plus button on the last node before the actual branches?

**Comment by kahboom** [comment]
@lhein I mentioned to you in the chat that this will be removed, you will only be able to use that button for adding branches if at least one branch exists, since right now it's confusing that it adds the step after all of the branches. See #1263 for more information.

**Comment by lhein** [comment]
my comment here was done earlier than the chat discussion. Ignore me.
