### ISSUE TITLE
Visualization: Branching Support

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#140]
## Description
This is an EPIC to add support for branching in the Visualization.

Depends on #193 and #270  <- this must be complete before branching can be fully implemented, though development can start before then.

## Business Requirements

- Branches can be started from any step (e.g. `START`, `MIDDLE`, `END`)
- There can be more than one branch from a single step
  - For example, with a `CHOICE` step, it's like `if`/`else`, so there will automatically be two branches, depending on the outcome of the condition
  - We don't yet support a "default flow" and "alternate flow", so the branches should each be equal weight in priority
- Branches contain steps, and those steps can be type `MIDDLE` or `END`
- If it's of type `MIDDLE`, then it should be merged back
  - Maria: It can merge back to any step, `MIDDLE` and `END` (well, I guess not `START`)
  - Just merged to the following step to that EIP unless it finishes in an `END`
  - Though not the most common scenario, it should be possible to have one branch that ends in `END`, and one branch that ends in `MIDDLE` and gets merged back

## Tasks

- [x] #782 
- [x] https://github.com/KaotoIO/kaoto-ui/issues/785
- [x] https://github.com/KaotoIO/kaoto-ui/issues/784
- [x] https://github.com/KaotoIO/kaoto-ui/issues/783
- [x] https://github.com/KaotoIO/kaoto-ui/issues/1158
- [x] https://github.com/KaotoIO/kaoto-ui/issues/786
- [x] https://github.com/KaotoIO/kaoto-ui/issues/1240
