### ISSUE TITLE
Support multiple routes in the same file

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-ui#801]
### Context
Sometimes files contain more than one route. The front end right now is not considering a second route that may be available on the same file.

We may need a dropdown with the list of routes in the file. But then, the source code we see will not be the complete list of routes. Or would it?

### Roadmap
- [x] Create a new store that handles multiple flows (#1748)
- [x] Add flows identifiers to individual flows and steps (#1727)
- [x] Add initial support for multiple flows (#1749)
- [x] Support editing steps (#1770)
- [x] Wire up new backend endpoints (#1823)
- [x] Bug: Opening a similar step brings previous information (#1823)
- [x] Delete all flows (#1763)
- [X] Remove previous IntegrationJSONStore (#1835)
- [X] Create a new flow (#1870)
- [X] Flows interaction (#1880)
    * List all flows
    * Delete a flow
    * Being able to hide/collapse flows
- [X] Review remaining methods and ensure tests cover everything
    * #1901
    * #1903

### Associated bugs
- https://github.com/KaotoIO/kaoto-ui/issues/1911
- https://github.com/KaotoIO/kaoto-ui/issues/1910
- https://github.com/KaotoIO/kaoto-ui/issues/1896
- https://github.com/KaotoIO/kaoto-ui/issues/1894

### Examples
<details>
  <summary>Example of a single route</summary>

```yaml
- from:
    uri: "timer:yaml"
    parameters:
      period: "1000"
    steps:
      - set-body:
          constant: "Hello Camel K from yaml"
      - to: "log:info"
```
</details>

<details>
  <summary>Example of multiple routes</summary>

```yaml
- from:
    uri: "timer:yaml"
    parameters:
      period: "1000"
    steps:
      - set-body:
          constant: "Hello Camel K from yaml"
      - to: "log:info"
- from:
    uri: "timer:anotherone"
    parameters:
      period: "50000"
    steps:
      - set-body:
          constant: "Nobody expects the second route!"
      - to: "log:info"
```
</details>

**Comment by brunoNetId** [comment]
I think this is a must.
it helps organised code and improve readability

**Comment by rstroop** [comment]
Most of the Camel I write has multiple routes. I'd like to add that if we create directs it would be nice to have a dotted line between those routes showing their connection.

**Comment by lordrip** [comment]
Related issue #1711
